import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'com.modrinth.minotaur' version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.18'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
}
loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        useLegacyMixinAp.set(false);
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
    }
}
modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${mod_id}"
    uploadFile = remapJar
    versionNumber = "${mod_version}-fabric"
    versionType = "${releaseType}"
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["fabric"]
    changelog = rootProject.file("changelog.md").text
    dependencies {
        required.project "fabric-api"
    }
}
tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    def mainFile = upload(curseforge_id, remapJar)
    mainFile.changelog = rootProject.file('changelog.md').text
    mainFile.addGameVersion(minecraft_version)
    mainFile.releaseType = "${releaseType}"
    mainFile.addModLoader("Fabric")
    mainFile.addRequirement("fabric-api")
}