import net.darkhax.curseforgegradle.TaskPublishCurseForge
plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.21'
    id 'net.darkhax.curseforgegradle' version '1.1.18'
    id 'com.modrinth.minotaur' version "2.+"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group

repositories {
    mavenLocal()
}

base {
    archivesName = name + "-neoforge"
}

neoForge {
    version = neo_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${mod_id}"
    uploadFile = jar
    versionName = "${minecraft_version}-${mod_version}"
    versionNumber = "${mod_version}"
    versionType = "${releaseType}"
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["neoforge"]
    changelog = rootProject.file("changelog.md").text
}

tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    def mainFile = upload(curseforge_id, jar)
    mainFile.changelog = rootProject.file('changelog.md').text
    mainFile.addGameVersion(minecraft_version)
    mainFile.releaseType = "${releaseType}"
    mainFile.displayName = "${minecraft_version}-${mod_version}"
    mainFile.addModLoader("NeoForge")
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

idea {
    module {
        downloadSources = false
        downloadJavadoc = true
    }
}