# Mod
mod_name=NullCore
mod_id=nullcore
mod_license=GPL-2.0
mod_version=1.21.4-0.2.8
mod_group=com.mw.nullcore
mod_authors=MW Team
mod_description=Utils API mod by MW Team.

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.138
neo_version_range=[21.4.0,)
loader_version_range=[4,)
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Publish
releaseType=release
curseforge_id=1286206

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false