# Project
group=com.mw.nullcore
java_version=21
license=GPL-2.0

# Publish
releaseType=release
curseforge_id=1286206

# Common
mod_version=1.21.4-0.1.1
minecraft_version=1.21.4
mod_name=NullCore
mod_author=MW Team
mod_id=nullcore
credits=
description=Utils API mod by MW Team.
minecraft_version_range=[1.21.4, 1.22)
parchment_minecraft=1.21.4
parchment_version=2025.01.05

# Fabric
fabric_version=0.114.2+1.21.4
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.4.135
neoforge_loader_version_range=[4,)
neo_form_version=1.21.4-20241203.161809

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
