import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'com.modrinth.minotaur' version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.18'
}
neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${mod_id}"
    uploadFile = jar
    versionNumber = "${mod_version}"
    versionType = "${releaseType}"
    gameVersions = ["${minecraft_version}"] as Iterable<? extends String>
    loaders = ["neoforge"]
    changelog = rootProject.file("changelog.md").text
}
tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    def projectId = "1286206"
    def mainFile = upload(projectId, jar)
    mainFile.changelog = rootProject.file('changelog.md').text
    mainFile.addGameVersion(minecraft_version)
    mainFile.releaseType = "${releaseType}"
    mainFile.addModLoader("NeoForge")
}